# configs/scenario/continual.yaml

train_mode   : continual
teacher_iters: 3
student_iters: 10
randaug_N    : 1
randaug_M    : 5

# Student LR 스케줄을 더 짧게
lr_warmup_epochs     : 2
student_warmup_epochs: 1

# 데이터가 작으므로 label smoothing 감소
label_smoothing      : 0.02

use_prev_kd        : true
prev_kd_alpha      : 0.5
prev_kd_temperature: 4.0

cb_finetune_epochs : 2
cb_finetune_lr     : 1e-4
