# configs/model/teacher/efficientnet_l2.yaml
model:
  teacher:
    name: efficientnet_l2
    pretrained: true
    lr: 1e-4
    weight_decay: 1e-4
    freeze_level: 0
    freeze_bn: false
    use_adapter: false
    use_checkpointing: true
