# configs/model/teacher/resnet152.yaml

model:
  teacher:
    name: resnet152
    pretrained: true
    lr: 1e-4
    weight_decay: 1e-4
    freeze_level: 0       # -1=off / 0=head / 1=layer4 / 2=layer3+4
    freeze_bn: false
    use_adapter: false
