# configs/fine_tune.yaml

device: "cuda"
dataset_name: "cifar100"
small_input: true        # 32x32 이미지에 맞게 stem stride를 1로 수정

# Teacher
teacher_name: "resnet101"
fine_tune_partial_freeze: false    # true 로 두면 backbone freeze, head만 학습

# ★—— CutMix/CE 파인튜닝 하이퍼파라미터 ——★
finetune_epochs: 50
finetune_lr: 0.001
finetune_weight_decay: 0.0005

# CutMix 설정
use_cutmix: true
cutmix_alpha: 1.0