# configs/registry_map.yaml

teachers:
  convnext_s:      models.teachers.convnext_s_teacher.create_convnext_s
  convnext_l:      models.teachers.convnext_l_teacher.create_convnext_l
  efficientnet_l2: models.teachers.efficientnet_l2_teacher.create_efficientnet_l2
  resnet152:       models.teachers.resnet152_teacher.create_resnet152

students:
  resnet152_pretrain: models.students.resnet152_student.create_resnet152_student
  resnet101_pretrain: models.students.resnet101_student.create_resnet101_student
  resnet50_scratch:   models.students.resnet50_student.create_resnet50_student
  shufflenet_v2_scratch: models.students.shufflenet_v2_student.create_shufflenet_v2_scratch_student
  mobilenet_v2_scratch:  models.students.mobilenet_v2_student.create_mobilenet_v2_scratch_student
  efficientnet_b0_scratch: models.students.efficientnet_b0_student.create_efficientnet_b0_scratch_student
