# configs/model/student/resnet50_scratch.yaml

model:
  student:
    name: resnet50
    pretrained: false
    lr: 8e-4
    weight_decay: 8e-4
    freeze_level: -1
    freeze_bn: false
    use_adapter: true

student_freeze_schedule: [-1, -1, -1]
